using System;
using NodaTime;
using Athi.Whippet.Adobe.Magento.Data;

namespace Athi.Whippet.Adobe.Magento.SalesRule
{
    /// <summary>
    /// Represents a coupon that can be applied to an order or item in Magento.
    /// </summary>
    public interface ISalesRuleCoupon : IMagentoEntity, IEqualityComparer<ISalesRuleCoupon>
    {
        /// <summary>
        /// Gets or sets the unique ID of the <see cref="ISalesRuleCoupon"/>.
        /// </summary>
        uint CouponID
        { get; set; }

        /// <summary>
        /// Gets or sets the parent <see cref="ISalesRule"/> that the coupon is associated with.
        /// </summary>
        ISalesRule Rule
        { get; set; }

        /// <summary>
        /// Gets or sets the coupon code.
        /// </summary>
        string Code
        { get; set; }

        /// <summary>
        /// Specifies the maximum amount of times the coupon can be used.
        /// </summary>
        uint? UsageLimit
        { get; set; }

        /// <summary>
        /// Specifies the maximum amount of times the coupon can be used per individual customer.
        /// </summary>
        uint? UsagePerCustomerLimit
        { get; set; }

        /// <summary>
        /// Represents a total number of instances the coupon was applied.
        /// </summary>
        uint TimesUsed
        { get; set; }

        /// <summary>
        /// Gets or sets the date the coupon is no longer valid.
        /// </summary>
        Instant? ExpirationDate
        { get; set; }

        /// <summary>
        /// Indicates whether the coupon is a primary coupon and should take precedence over other applied coupons on an order.
        /// </summary>
        bool IsPrimary
        { get; set; }

        /// <summary>
        /// Gets or sets the date/time the entry was created.
        /// </summary>
        Instant? CreatedAt
        { get; set; }

        /// <summary>
        /// Gets or sets the coupon type code.
        /// </summary>
        short? Type
        { get; set; }

        /// <summary>
        /// Indicates whether the coupon was generated by DotMailer.
        /// </summary>
        bool? GeneratedByDotMailer
        { get; set; }
    }
}
