IF NOT EXISTS (SELECT name FROM master.sys.databases WHERE name = N'$$WHIPPET$$')
BEGIN 
    CREATE DATABASE [$$WHIPPET$$]
     CONTAINMENT = NONE
     WITH CATALOG_COLLATION = DATABASE_DEFAULT

    IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
    BEGIN
        EXEC [$$WHIPPET$$].[dbo].[sp_fulltext_database] @action = 'enable'
    END
    
    ALTER DATABASE [$$WHIPPET$$] SET ANSI_NULL_DEFAULT OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET ANSI_NULLS OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET ANSI_PADDING OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET ANSI_WARNINGS OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET ARITHABORT OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET AUTO_CLOSE OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET AUTO_SHRINK OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET AUTO_UPDATE_STATISTICS ON 
    

    ALTER DATABASE [$$WHIPPET$$] SET CURSOR_CLOSE_ON_COMMIT OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET CURSOR_DEFAULT  GLOBAL 
    

    ALTER DATABASE [$$WHIPPET$$] SET CONCAT_NULL_YIELDS_NULL OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET NUMERIC_ROUNDABORT OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET QUOTED_IDENTIFIER OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET RECURSIVE_TRIGGERS OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET  DISABLE_BROKER 
    

    ALTER DATABASE [$$WHIPPET$$] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET DATE_CORRELATION_OPTIMIZATION OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET TRUSTWORTHY OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET ALLOW_SNAPSHOT_ISOLATION OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET PARAMETERIZATION SIMPLE 
    

    ALTER DATABASE [$$WHIPPET$$] SET READ_COMMITTED_SNAPSHOT OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET HONOR_BROKER_PRIORITY OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET RECOVERY FULL 
    

    ALTER DATABASE [$$WHIPPET$$] SET  MULTI_USER 
    

    ALTER DATABASE [$$WHIPPET$$] SET PAGE_VERIFY CHECKSUM  
    

    ALTER DATABASE [$$WHIPPET$$] SET DB_CHAINING OFF 
    

    ALTER DATABASE [$$WHIPPET$$] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
    

    ALTER DATABASE [$$WHIPPET$$] SET TARGET_RECOVERY_TIME = 60 SECONDS 
    

    ALTER DATABASE [$$WHIPPET$$] SET DELAYED_DURABILITY = DISABLED 
    

    ALTER DATABASE [$$WHIPPET$$] SET ACCELERATED_DATABASE_RECOVERY = OFF  
    

    ALTER DATABASE [$$WHIPPET$$] SET QUERY_STORE = OFF
    

    ALTER DATABASE [$$WHIPPET$$] SET  READ_WRITE 
    
END
GO


USE [$$WHIPPET$$]
GO

IF NOT EXISTS (SELECT * FROM [$$WHIPPET$$].sys.schemas WHERE name = 'whippet')
BEGIN
    EXEC('CREATE SCHEMA [whippet]');
END

IF (SELECT COUNT(*) FROM [$$WHIPPET$$].[sys].[database_principals] WHERE [name]='whippet_sa') = 0
BEGIN
    BEGIN TRY
        CREATE USER [whippet_sa] FOR LOGIN [whippet_sa] WITH DEFAULT_SCHEMA=[whippet]
    END TRY
    BEGIN CATCH
        SELECT @@ERROR
    END CATCH
END

BEGIN TRY
    ALTER AUTHORIZATION ON SCHEMA::[db_owner] TO [whippet_sa]
END TRY
BEGIN CATCH
    SELECT @@ERROR
END CATCH

BEGIN TRY
    ALTER AUTHORIZATION ON SCHEMA::[whippet] TO [whippet_sa]
END TRY
BEGIN CATCH
    SELECT @@ERROR
END CATCH

BEGIN TRY
    ALTER ROLE [db_owner] ADD MEMBER [whippet_sa]
END TRY
BEGIN CATCH
    SELECT @@ERROR
END CATCH

-- Super Duper Framework: Start

IF NOT EXISTS (SELECT * FROM [$$WHIPPET$$].sys.schemas WHERE name = 'Athi')
BEGIN
    EXEC('CREATE SCHEMA [Athi]');
END

BEGIN TRY
    ALTER AUTHORIZATION ON SCHEMA::[Athi] TO [whippet_sa]
END TRY
BEGIN CATCH
    SELECT @@ERROR
END CATCH

-- Super Duper Framework: End
